### ISSUE TITLE
Suggesting new feature: rolling file per {DateHour}

### ISSUE THREAD

**Issue by jose3m** [serilog/serilog-sinks-rollingfile#22]
Hi.

First of all I want to give you congratulations for the good work.

The default (and only) {Date} specifier is very usefull for the most situations but now I have one need: to be able to generate more than one file per day. My problem is the big amount of data I am storing that causes to save big files or just ignore data once a daily file has reached the limit size.

One option I suggest could be to add a new {DateHour} specifier (maintaining the current {Date} specifier as the default one, assuring compatibility with previous versions) with the format "yyyyMMddHH" (24 hours format).

What do you think about it?

If you prefer I can do a PR.

Thank you.

**Comment by nblumhardt** [comment]
Thanks for getting in touch! This has come up a few times, and recently we've had some discussions about making `RollingFile` a bit more flexible, which this would come under.

The bar for making changes in this sink is still very high, but I think we could do this if the PR is very surgical and doesn't significantly change the structure of `RollingFileSink`.

The kind of change I'm anticipating is:
- Delegate `_nextCheckpoint` calculation to `TemplatedPathRoller` instead of adding one day in `RollingFileSink`
- Renaming `RollingLogFile.Date` to `RollingLogFile.DateTime`
- All other changes in `TemplatedPathRoller`.

Does this match what you had in mind?

What do you think of using the token `{Hour}` instead of `{DateHour}`? Any token we use for the time-based part of the filename will need to be completely self-describing and lexicographically sortable anyway, so there will never (that I can imagine) be an `{Hour}` token that means anything different from your proposed format for `{DateHour}`. I think `{Hour}` is a bit more guessable.

**Comment by jose3m** [comment]
Hi.

For me it is ok to use {Hour} instead of {DateHour} and the change should be very similar to what you comment.

**Comment by nblumhardt** [comment]
That's awesome, thanks Jose.

**Comment by Katulus** [comment]
Hello,
I found this topic when I was looking for something similar. However my requirement is little further. Not having just hour but support full `DateTime` formatting, such as you can do for `{Timestamp:yyyy-MM-dd HH:mm:ss}` in log messages. The reason is that I need a new log file with each application start, not mixing multiple application runs into one file. 
@jose3m, if you do the PR and can squeeze full formatting support in there it would be awesome. If not I may be able to look at it later.

**Comment by nblumhardt** [comment]
Hi Jiri - thanks for the input. I don't think the change you're suggesting would fit with the one being discussed here. If you're keen to discuss the scenario, would you mind opening a fresh ticket? I will see what ideas I can come up with for supporting file-per-run. Thanks!

**Comment by Katulus** [comment]
Created new issue #26 - Suggesting new feature: rolling file per run

**Comment by nblumhardt** [comment]
Merged in #29.
