### ISSUE TITLE
Logger stops writing when file size limit reached

### ISSUE THREAD

**Issue by AlexanderMuller** [serilog/serilog-sinks-rollingfile#27]
Isn't the rolling file supposed to tail entries and when file limit is reached delete lines from the head?

This isn't the case and the logger stops writing when the file limit is reached.

**Comment by nblumhardt** [comment]
No, the behavior's by design. The size limit is not for rolling the file contents, but to prevent runaway disk usage if for example the app gets stuck in an infinite loop.

When such a thing occurs (logging in an infinite loop) the log file will be useless in diagnosing why it happened if the only things in the log file are the events generated in the loop. By dropping the overflowing events but keeping the earlier ones, the history leading up to the problem is retained.

I think the feature you're looking for is called "roll on file size" - see: https://github.com/BedeGaming/sinks-rollingfile

Cheers!
Nick
