### ISSUE TITLE
Suggestion to not add the {Date} specifier automatically

### ISSUE THREAD

**Issue by guardrex** [serilog/serilog-sinks-rollingfile#3]
Regarding the `{Date}` specifier:

https://github.com/serilog/serilog-sinks-rollingfile/blob/master/src/Serilog.Sinks.RollingFile/Sinks/RollingFile/TemplatedPathRoller.cs#L56

If one **doesn't** add the `{Date}` specifier to the path, perhaps because the dev doesn't want the immutable format of `yyyyMMdd`, you add it automatically, and the dev ends up with two dates ... their own ... and your's tacked on at the end. I think if the dev doesn't add `{Date}` to the path, then you shouldn't presume to add it.

**Comment by nblumhardt** [comment]
Thanks for the feedback! Unfortunately, to roll sensibly we need the filename to vary by date - the simple rolling file sink here doesn't accommodate other rolling strategies.

We have stuck to this notion because there are so many variations. In the long run having alternatives like [this one](https://github.com/BedeGaming/sinks-rollingfile) can provide the same choice of strategy without this sink becoming a spaghettified mess.

What do you think about fitting out a fork/alternative to support the other strategy? Cheers!
