### ISSUE TITLE
Log saved in syswow64, when started as service

### ISSUE THREAD

**Issue by ghost** [serilog/serilog-sinks-rollingfile#64]
Hey,
I configured my serilog in the app.config with these settings:

    <add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />
    <add key="serilog:write-to:RollingFile.pathFormat" value="logs\log-{Date}.txt" />

Logger created with:
  _logger = new LoggerConfiguration()
                .ReadFrom.AppSettings()
                .CreateLogger();

If i start the executable, serilog loggs to the directory where the .exe is placed.
But if i use Topfshelf and start the program as a service, serilog writes to "C:\Windows\SysWOW64\logs"

I want to configure the log-location in the appsettings, without environment variables.
Are there any ways?

Thank you!

**Comment by tsimbalar** [comment]
Hi Tobias, 

I think it is "by design", by default, the current working directory of Windows Services is something like `C:\Windows\SysWOW64` or `C:\Windows\System32`... 

On this blog post, Phil Haack ( @haacked ) sets it to something else (`System.AppDomain.CurrentDomain.BaseDirectory`) when the application starts,  maybe that could help : https://haacked.com/archive/2004/06/29/current-directory-for-windows-service-is-not-what-you-expect.aspx/ .

I hope this helps !

Also, *Serilog.Sinks.File* is now the recommended way of logging to files. While *Serilog.Sinks.RollingFile* is still supported the future efforts will be targetted to the other one. See this article for more info : https://nblumhardt.com/2017/10/serilog-file-logging/
